from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
import c2pa
import io
import json

app = FastAPI(title="Otter Truth API 🦦")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def home():
    return {"status": "online", "message": "Otter pool is ready! 🦦"}

@app.post("/inspect")
async def inspect_file(file: UploadFile = File(...)):
    contents = await file.read()

    c2pa_json_str = None
    try:
        reader = c2pa.Reader(file.filename, io.BytesIO(contents))
        c2pa_json_str = reader.json()
    except Exception:
        c2pa_json_str = None

    if not c2pa_json_str:
        return {
            "filename": file.filename,
            "has_c2pa_manifest": False,
            "is_ai": False,
            "otter_verdict": "🟡 No C2PA Manifest Found\nMetadata was stripped or the file is unsigned. Stand by for Tier 2 pixel forensics."
        }

    # Parse C2PA JSON string
    manifest = json.loads(c2pa_json_str) if isinstance(c2pa_json_str, str) else c2pa_json_str

    # Convert manifest to string to scan for standard AI markers (IPTC / C2PA tags)
    manifest_str = json.dumps(manifest).lower()

    is_ai_generated = any(term in manifest_str for term in [
        "trainedalgorithmicmedia",
        "compositeWithTrainedAlgorithmicMedia",
        "dall-e",
        "midjourney",
        "stable diffusion",
        "c2pa.ai"
    ])

    if is_ai_generated:
        verdict = "🤖 Generated by AI\nC2PA Manifest confirms synthetic creation (e.g. DALL-E/OpenAI)."
    else:
        verdict = "✅ Authentic Provenance\nC2PA Manifest confirms genuine device capture / camera chain of custody."

    return {
        "filename": file.filename,
        "has_c2pa_manifest": True,
        "is_ai": is_ai_generated,
        "c2pa_details": manifest,
        "otter_verdict": verdict
    }