from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
import c2pa
import io
import json
import requests

app = FastAPI(title="Otter Truth API 🦦")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Optional Tier 2 Inference Endpoint (e.g. HuggingFace / OmniRoute / Custom Model)
TIER2_INFERENCE_URL = "https://api-inference.huggingface.co/models/lynx-ai/ai-image-detector"
# Set your API token if using Hugging Face or an auth-protected route
HF_API_TOKEN = "your_hf_token_here" 

def run_tier2_forensics(image_bytes: bytes) -> dict:
    """Fallback pixel analysis when C2PA metadata is missing."""
    headers = {"Authorization": f"Bearer {HF_API_TOKEN}"} if HF_API_TOKEN else {}
    try:
        response = requests.post(TIER2_INFERENCE_URL, headers=headers, data=image_bytes, timeout=10)
        if response.status_code == 200:
            # Expected response format: [{'label': 'Artificial', 'score': 0.98}, ...]
            results = response.json()
            top_prediction = results[0] if isinstance(results, list) and len(results) > 0 else {}
            label = top_prediction.get("label", "").lower()
            score = top_prediction.get("score", 0.0)
            
            is_ai = "artificial" in label or "fake" in label or "generated" in label
            return {
                "success": True,
                "is_ai": is_ai,
                "confidence": round(score * 100, 1)
            }
    except Exception as e:
        print(f"Tier 2 request failed: {e}")
        
    return {"success": False, "is_ai": False, "confidence": 0}


@app.post("/inspect")
async def inspect_file(file: UploadFile = File(...)):
    contents = await file.read()
    
    # --- TIER 1: C2PA MANIFEST CHECK ---
    c2pa_json_str = None
    try:
        reader = c2pa.Reader(file.filename, io.BytesIO(contents))
        c2pa_json_str = reader.json()
    except Exception:
        c2pa_json_str = None

    if c2pa_json_str:
        manifest_str = str(c2pa_json_str).lower()
        ai_keywords = ["trainedalgorithmicmedia", "openai", "dall-e", "midjourney", "stable diffusion", "c2pa.ai"]
        is_ai = any(kw in manifest_str for kw in ai_keywords)

        if is_ai:
            verdict = "🤖 Generated by AI\n(Tier 1: C2PA Manifest confirms synthetic creation)"
        else:
            verdict = "✅ Genuine Capture\n(Tier 1: C2PA Manifest confirms hardware provenance)"

        return {
            "filename": file.filename,
            "tier_used": 1,
            "has_c2pa_manifest": True,
            "is_ai": is_ai,
            "otter_verdict": verdict
        }

    # --- TIER 2: PIXEL FORENSICS FALLBACK ---
    tier2_result = run_tier2_forensics(contents)
    
    if tier2_result["success"]:
        if tier2_result["is_ai"]:
            verdict = f"🤖 Likely AI-Generated ({tier2_result['confidence']}% confidence)\n(Tier 2: Pixel forensics fallback)"
        else:
            verdict = f"📸 Likely Real Photo ({tier2_result['confidence']}% confidence)\n(Tier 2: Pixel forensics fallback)"
    else:
        verdict = "🟡 No C2PA Manifest Found\n(Metadata stripped and Tier 2 fallback unreachable)"

    return {
        "filename": file.filename,
        "tier_used": 2,
        "has_c2pa_manifest": False,
        "is_ai": tier2_result.get("is_ai", False),
        "otter_verdict": verdict
    }